Day5 challenge: Work on package numpy

    -1st make different kind of arrays constructors
    -2nd mathematic operation with arrays
    -3rd Linear algebra

In [26]:
import numpy as np  # importation of numpy package 

Different Kind of arrays constructors

In [22]:
# 1D array with (array, zeros, ones, random.randn) constructor
A = np.array([-1, +1, +1, -1])
A

array([-1,  1,  1, -1])

In [23]:
B = np.zeros((4,))
B

array([0., 0., 0., 0.])

In [24]:
C = np.ones((4,))
C

array([1., 1., 1., 1.])

In [25]:
D = np.random.randn(4, )
D

array([-0.2772183 , -2.59315792, -1.17531583, -0.78581471])

In [35]:
E = np.linspace(0, 1, num= 10, dtype= np.float16)
E

array([0.    , 0.1111, 0.2222, 0.3333, 0.4443, 0.5557, 0.6665, 0.778 ,
       0.8887, 1.    ], dtype=float16)

In [36]:
F = np.arange(1, 2, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [41]:
# 2D array 
a = np.array([[1, 2, 3], [1, 2, np.nan]])
a

array([[ 1.,  2.,  3.],
       [ 1.,  2., nan]])

In [54]:
# Array manipulation
AB = np.vstack((A, B))
AB

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [59]:
AC = np.vstack((A, C))
AC

array([[-1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.]])

In [53]:
C.shape

(4,)

In [64]:
BC = np.concatenate((B, C), axis = 0) #We can't concatenate B and C on axis 1 because they are not a 2D arrays
BC

array([0., 0., 0., 0., 1., 1., 1., 1.])

Mathematics Operations with array